In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
# Import required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option('display.max_columns', None)

In [3]:
df=pd.read_csv('/content/drive/MyDrive/Projects/Kaggle/02. House Price Prediction/01. DataSet/train.csv')
print('Shape:',df.shape)
df.sample(5)

Shape: (1460, 81)


Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
557    558          50  C (all)         60.0    11040   Pave   NaN      Reg   
718    719          60       RL         96.0    10542   Pave   NaN      Reg   
1412  1413          90       RL         60.0     7200   Pave   NaN      Reg   
1370  1371          50       RL         90.0     5400   Pave   NaN      Reg   
974    975          70       RL         60.0    11414   Pave   NaN      IR1   

     LandContour Utilities LotConfig LandSlope Neighborhood Condition1  \
557          Low    AllPub    Inside       Mod       IDOTRR       Norm   
718          Lvl    AllPub    Inside       Gtl      NoRidge       Norm   
1412         Lvl    AllPub    Inside       Gtl        NAmes       Norm   
1370         Lvl    AllPub    Corner       Gtl      OldTown     Artery   
974          Lvl    AllPub    Corner       Gtl      BrkSide       RRAn   

     Condition2 BldgType HouseStyle  OverallQual  OverallCond  YearBuilt  \
557        Norm     1Fam     1.5Fin            4            6       1920   
718        Norm     1Fam     2Story            7            5       1993   
1412       Norm   Duplex     1Story            4            5       1949   
1370       Norm     1Fam     1.5Fin            4            6       1920   
974       Feedr     1Fam     2Story            7            8       1910   

      YearRemodAdd RoofStyle RoofMatl Exterior1st Exterior2nd MasVnrType  \
557           1950     Gable  CompShg     MetalSd     MetalSd       None   
718           1994       Hip  CompShg     Wd Sdng     ImStucc    BrkFace   
1412          1950     Gable  CompShg     BrkFace       Stone       None   
1370          1950     Gable  CompShg      CBlock      CBlock       None   
974           1993     Gable  CompShg     HdBoard     HdBoard       None   

      MasVnrArea ExterQual ExterCond Foundation BsmtQual BsmtCond  \
557          0.0        TA        TA     CBlock       TA       TA   
718        651.0        Gd        TA      PConc       Gd       TA   
1412         0.0        TA        TA       Slab      NaN      NaN   
1370         0.0        Fa        TA      PConc       TA       TA   
974          0.0        TA        Gd     BrkTil       Gd       TA   

     BsmtExposure BsmtFinType1  BsmtFinSF1 BsmtFinType2  BsmtFinSF2  \
557            No          Rec         637          Unf           0   
718            Gd          GLQ        1173          Unf           0   
1412          NaN          NaN           0          NaN           0   
1370           No          ALQ         315          Rec         105   
974            No          Unf           0          Unf           0   

      BsmtUnfSF  TotalBsmtSF Heating HeatingQC CentralAir Electrical  \
557           0          637    GasA        Gd          Y      SBrkr   
718         138         1311    GasA        Ex          Y      SBrkr   
1412          0            0    Wall        Fa          N      FuseF   
1370        420          840    GasA        Ex          Y      SBrkr   
974         728          728    GasA        TA          N      SBrkr   

      1stFlrSF  2ndFlrSF  LowQualFinSF  GrLivArea  BsmtFullBath  BsmtHalfBath  \
557        897       439             0       1336             0             0   
718       1325      1093             0       2418             1             0   
1412      1040         0             0       1040             0             0   
1370       840       534             0       1374             0             0   
974       1136       883             0       2019             0             0   

      FullBath  HalfBath  BedroomAbvGr  KitchenAbvGr KitchenQual  \
557          1         1             3             1          TA   
718          2         1             3             1          Gd   
1412         2         0             2             2          TA   
1370         1         0             2             1          TA   
974          1         0             3             1          Gd   

   

In [ ]:
#df.info()

In [4]:
#Categorizing columns into Numerical or Categorical (norminal/ordinal) data types 

numerical_columns= ['Id', 'LotFrontage', 'LotArea','MasVnrArea','BsmtFinSF1','BsmtFinSF2','BsmtUnfSF','TotalBsmtSF','1stFlrSF','2ndFlrSF','LowQualFinSF','GrLivArea','BsmtFullBath','BsmtHalfBath','FullBath','HalfBath','Bedroom','Kitchen','TotRmsAbvGrd','Fireplaces','GarageCars','GarageArea','WoodDeckSF','OpenPorchSF','EnclosedPorch','3SsnPorch','ScreenPorch','PoolArea','MiscVal']
categorical_nominal_columns= ['MSSubClass','LotShape', 'OverallQual','OverallCond','ExterQual','ExterCond','BsmtQual','BsmtCond','BsmtExposure','BsmtFinType1','BsmtFinType2','HeatingQC','CentralAir','KitchenQual','FireplaceQu','GarageFinish','GarageQual','GarageCond','PavedDrive','PoolQC','Fence']
categorical_ordinal_columns= ['MSZoning', 'Street', 'Alley','LandContour', 'Utilities', 'LotConfig','LandSlope','Neighborhood', 'Condition1','Condition2','BldgType','HouseStyle','RoofStyle','RoofMatl','Exterior1st','Exterior2nd','MasVnrType','Foundation','Heating','Electrical','Functional','GarageType','MiscFeature','SaleType','SaleCondition']
#Some of ordinal columns could be nominal which can only be identified by checking comparing it with the output

output_column= ['SalePrice']

## 1. Converting categorical nominal columns to numerical columns by label encoding

This will help in finding the correlation to the output and ease the feature selection process

In [5]:
def LotShape(val):
  lables={'Reg':3,'IR1':2,'IR2':3,'IR3':4}
  if val in lables: return lables[val]
  else:return val

def Multiple(val):
  lables={'Ex':5,'Gd':4,'TA':3,'Fa':2,'Po':1,'NA':0}
  if val in lables: return lables[val]
  else:return val

def BsmtExposure(val):
  lables={'Gd':4,'Av':3,'Mn':2,'No':1,'NA':0}
  if val in lables: return lables[val]
  else:return val

def BsmtFinType(val):
  lables={'GLQ':6,'ALQ':5,'BLQ':4,'Rec':3,'LwQ':2,'Unf':1,'NA':0}
  if val in lables: return lables[val]
  else:return val

def CentralAir(val):
  lables={'Y':1,'N':0}
  if val in lables: return lables[val]
  else:return val

def GarageFinish(val):
  lables={'Fin':3,'RFn':2,'Unf':1,'NA':0}
  if val in lables: return lables[val]
  else:return val

def PavedDrive(val):
  lables={'Y':2,'P':1,'N':0}
  if val in lables: return lables[val]
  else:return val

def Fence(val):
  lables={'GdPrv':4,'MnPrv':3,'GdWo':2,'MnWw':1,'NA':0}
  if val in lables: return lables[val]
  else:return val

df['LotShape']=df['LotShape'].apply(LotShape)
df['BsmtExposure']=df['BsmtExposure'].apply(BsmtExposure)
df['BsmtFinType1']=df['BsmtFinType1'].apply(BsmtFinType)
df['BsmtFinType2']=df['BsmtFinType2'].apply(BsmtFinType)
df['CentralAir']=df['CentralAir'].apply(CentralAir)
df['GarageFinish']=df['GarageFinish'].apply(GarageFinish)
df['PavedDrive']=df['PavedDrive'].apply(PavedDrive)
df['Fence']=df['Fence'].apply(Fence)
df['ExterQual']=df['ExterQual'].apply(Multiple)
df['ExterCond']=df['ExterCond'].apply(Multiple)
df['BsmtQual']=df['BsmtQual'].apply(Multiple)
df['BsmtCond']=df['BsmtCond'].apply(Multiple)
df['HeatingQC']=df['HeatingQC'].apply(Multiple)
df['KitchenQual']=df['KitchenQual'].apply(Multiple)
df['FireplaceQu']=df['FireplaceQu'].apply(Multiple)
df['GarageQual']=df['GarageQual'].apply(Multiple)
df['GarageCond']=df['GarageCond'].apply(Multiple)
df['PoolQC']=df['PoolQC'].apply(Multiple)

In [6]:
for i in categorical_nominal_columns:
  print(i)
  print(df[i].unique())

MSSubClass
[ 60  20  70  50 190  45  90 120  30  85  80 160  75 180  40]
LotShape
[3 2 4]
OverallQual
[ 7  6  8  5  9  4 10  3  1  2]
OverallCond
[5 8 6 7 4 2 3 9 1]
ExterQual
[4 3 5 2]
ExterCond
[3 4 2 1 5]
BsmtQual
[ 4.  3.  5. nan  2.]
BsmtCond
[ 3.  4. nan  2.  1.]
BsmtExposure
[ 1.  4.  2.  3. nan]
BsmtFinType1
[ 6.  5.  1.  3.  4. nan  2.]
BsmtFinType2
[ 1.  4. nan  5.  3.  2.  6.]
HeatingQC
[5 4 3 2 1]
CentralAir
[1 0]
KitchenQual
[4 3 5 2]
FireplaceQu
[nan  3.  4.  2.  5.  1.]
GarageFinish
[ 2.  1.  3. nan]
GarageQual
[ 3.  2.  4. nan  5.  1.]
GarageCond
[ 3.  2. nan  4.  1.  5.]
PavedDrive
[2 0 1]
PoolQC
[nan  5.  2.  4.]
Fence
[nan  3.  2.  4.  1.]


## 2. Handling Nulls

In [7]:
check=df.isnull().sum()
column_names=check.index
null_count=check.values
null_columns=[]

for i in range (0,len(null_count)):
  if(null_count[i]!=0):
    null_columns.append(column_names[i])

null_columns

['LotFrontage',
 'Alley',
 'MasVnrType',
 'MasVnrArea',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Electrical',
 'FireplaceQu',
 'GarageType',
 'GarageYrBlt',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PoolQC',
 'Fence',
 'MiscFeature']

In [8]:
df[null_columns].isnull().sum()

LotFrontage      259
Alley           1369
MasVnrType         8
MasVnrArea         8
BsmtQual          37
BsmtCond          37
BsmtExposure      38
BsmtFinType1      37
BsmtFinType2      38
Electrical         1
FireplaceQu      690
GarageType        81
GarageYrBlt       81
GarageFinish      81
GarageQual        81
GarageCond        81
PoolQC          1453
Fence           1179
MiscFeature     1406
dtype: int64

How to handle nulls?
1. Houses with no basement have nulls in basement related columns. So, replace them with 0.
2. Houses with no garage have nulls in basement related columns. So, replace them with 'NoGrg' oo 0. Filling GarageYrBlt with the column's mode: 2005.
3. Houses with no Masonry veneer have nulls in Masonry veneer related columns. So, replace them with 'None' oo 0.
4. Replacing Lotfootage with it's mode
5. Almost 80% of Alley, FireplaceQu, PoolQC, Fence and MuscFeature columns are empty and rows with non-null values does not show significant output. Hence, it's safe to drop this column.
6. 91% of electrical column is SBrkr and hence replacing the 1 null row with the same

In [9]:
# Dropping columns with high # nulls
drop_coulmns=['Alley','PoolQC','Fence','MiscFeature','FireplaceQu']
df.drop(drop_coulmns,axis=1,inplace=True)
null_columns=set(null_columns)-set(drop_coulmns)

In [10]:
#Replacing Nulls 
null_fillers={'BsmtQual':0,'BsmtCond':0,'BsmtExposure':0,'BsmtFinType1':0,'BsmtFinType2':0,'GarageType':'NoGrg','GarageYrBlt':2005,'GarageFinish':0,'GarageQual':0,'GarageCond':0,'LotFrontage':60,'MasVnrType':'None','MasVnrArea':0,'Electrical':'SBrkr'}

for i in null_columns:
  df[i].fillna(null_fillers[i],inplace=True)

check=df.isnull().any()
null_check=check.values
null_check

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False])

In [11]:
df.sample(5)

Id  MSSubClass MSZoning  LotFrontage  LotArea Street  LotShape  \
389    390          60       RL         96.0    12474   Pave         3   
349    350          60       RL         56.0    20431   Pave         3   
520    521         190       RL         60.0    10800   Pave         3   
1152  1153          20       RL         90.0    14115   Pave         2   
589    590          40       RM         50.0     9100   Pave         3   

     LandContour Utilities LotConfig LandSlope Neighborhood Condition1  \
389          Lvl    AllPub    Inside       Gtl      NridgHt       Norm   
349          Lvl    AllPub    Inside       Gtl      NridgHt       Norm   
520          Lvl    AllPub    Inside       Gtl      OldTown       Norm   
1152         Lvl    AllPub    Inside       Gtl      Crawfor       Norm   
589          Lvl    AllPub    Inside       Gtl      BrkSide       RRAn   

     Condition2 BldgType HouseStyle  OverallQual  OverallCond  YearBuilt  \
389        Norm     1Fam     2Story           10            5       2007   
349        Norm     1Fam     2Story            9            5       2005   
520        Norm   2fmCon     2Story            4            7       1900   
1152       Norm     1Fam     1Story            6            7       1956   
589       Feedr     1Fam     1Story            5            6       1930   

      YearRemodAdd RoofStyle RoofMatl Exterior1st Exterior2nd MasVnrType  \
389           2008     Gable  CompShg     VinylSd     VinylSd      Stone   
349           2006       Hip  CompShg     CemntBd     CmentBd    BrkFace   
520           2000     Gable  CompShg     MetalSd     MetalSd       None   
1152          2004     Gable  CompShg       Stone       Stone       None   
589           1960     Gable  CompShg     VinylSd     VinylSd       None   

      MasVnrArea  ExterQual  ExterCond Foundation  BsmtQual  BsmtCond  \
389        272.0          5          3      PConc       5.0       3.0   
349        870.0          5          3      PConc       5.0       3.0   
520          0.0          3          3     BrkTil       0.0       0.0   
1152         0.0          3          3      PConc       3.0       3.0   
589          0.0          3          3     BrkTil       3.0       3.0   

      BsmtExposure  BsmtFinType1  BsmtFinSF1  BsmtFinType2  BsmtFinSF2  \
389            3.0           6.0        1280           1.0           0   
349            1.0           6.0        1410           1.0           0   
520            0.0           0.0           0           0.0           0   
1152           1.0           5.0         296           6.0         547   
589            1.0           1.0           0           1.0           0   

      BsmtUnfSF  TotalBsmtSF Heating  HeatingQC  CentralAir Electrical  \
389         402         1682    GasA          5           1      SBrkr   
349         438         1848    GasA          5           1      SBrkr   
520           0            0    GasA          3           0      FuseA   
1152        230         1073    GasA          5           1      SBrkr   
589         742          742    GasA          3           1      FuseA   

      1stFlrSF  2ndFlrSF  LowQualFinSF  GrLivArea  BsmtFullBath  BsmtHalfBath  \
389       1742       590             0       2332             1             0   
349       1848       880             0       2728             1             0   
520        694       600             0       1294             0             0   
1152      1811         0             0       1811             0             0   
589        779         0           156        935             0             0   

      FullBath  HalfBath  BedroomAbvGr  KitchenAbvGr  KitchenQual  \
389          2         1             3             1            5   
349          2         1             4             1            5   
520          2         0             3             2            3   
1152         1         0             2             1            5   
589          1         0             2     

### 3. Converting date columns to numberical columns & seperating output column

Date columns that needed to be handled:
1. YearBuilt - Subtract it with YrSold and use it as a numerical column
2. YearRemodAdd - Subtract it with YrSold and use it as a numerical column
3. GarageYrBlt- Subtract it with YrSold and use it as a numerical column
4. MoSold - not needed after executing 1,2 & 3 
5. YrSold - not needed after executing 1,2 & 3



In [12]:
df['House_age_from_built']=df['YrSold']-df['YearBuilt']
df['House_age_from_Modified']=df['YrSold']-df['YearRemodAdd']
df.drop(['YearBuilt','YrSold','YearRemodAdd'],axis=1, inplace=True)

#Sepearating 'SalePrice' as the output column
df_op = pd.DataFrame(df.pop('SalePrice'))
df_ip=df.copy()

df_ip.sample(10)

Id  MSSubClass MSZoning  LotFrontage  LotArea Street  LotShape  \
740    741          70       RM         60.0     9600   Pave         3   
428    429          20       RL         64.0     6762   Pave         3   
664    665          20       RL         49.0    20896   Pave         3   
1321  1322          20       RL         60.0     6627   Pave         2   
654    655          20       RL         91.0    10437   Pave         2   
1368  1369         120       RM         60.0     4435   Pave         3   
1411  1412          50       RL         80.0     9600   Pave         3   
584    585          50       RM         51.0     6120   Pave         3   
956    957         160       RM         24.0     1300   Pave         3   
760    761          20       RL         70.0     9100   Pave         3   

     LandContour Utilities LotConfig LandSlope Neighborhood Condition1  \
740          Lvl    AllPub    Inside       Gtl      OldTown       Norm   
428          Lvl    AllPub    Inside       Gtl      CollgCr       Norm   
664          Lvl    AllPub   CulDSac       Gtl      Somerst       RRAn   
1321         Lvl    AllPub    Corner       Gtl      BrkSide      Feedr   
654          Lvl    AllPub    Inside       Gtl      NoRidge       Norm   
1368         Lvl    AllPub    Inside       Gtl      CollgCr       Norm   
1411         Lvl    AllPub    Inside       Gtl        NAmes       Norm   
584          Lvl    AllPub    Inside       Gtl      BrkSide       Norm   
956          Lvl    AllPub    Inside       Gtl      Blueste       Norm   
760          Lvl    AllPub    Inside       Gtl        NAmes       Norm   

     Condition2 BldgType HouseStyle  OverallQual  OverallCond RoofStyle  \
740        Norm     1Fam     2Story            5            7     Gable   
428        Norm     1Fam     1Story            7            5     Gable   
664        Norm     1Fam     1Story            8            5     Gable   
1321       Norm     1Fam     1Story            3            6       Hip   
654        Norm     1Fam     1Story            8            6       Hip   
1368       Norm   TwnhsE     1Story            6            5     Gable   
1411       Norm     1Fam     1.5Fin            6            8     Gable   
584        Norm     1Fam     1.5Fin            4            7     Gable   
956        Norm   TwnhsE     2Story            6            6     Gable   
760        Norm     1Fam     1Story            6            6       Hip   

     RoofMatl Exterior1st Exterior2nd MasVnrType  MasVnrArea  ExterQual  \
740   CompShg     Wd Sdng     Wd Shng       None         0.0          3   
428   CompShg     VinylSd     VinylSd    BrkFace       108.0          4   
664   CompShg     VinylSd     VinylSd       None         0.0          4   
1321  CompShg     VinylSd     VinylSd       None         0.0          3   
654   CompShg     MetalSd     MetalSd    BrkFace       660.0          4   
1368  CompShg     VinylSd     VinylSd    BrkFace       170.0          4   
1411  CompShg     VinylSd     VinylSd       None         0.0          3   
584   CompShg     AsbShng     AsbShng       None         0.0          3   
956   CompShg     MetalSd     MetalSd       None         0.0          3   
760   CompShg     Wd Sdng     Wd Sdng       None         0.0          3   

      ExterCond Foundation  BsmtQual  BsmtCond  BsmtExposure  BsmtFinType1  \
740           4     BrkTil       2.0       2.0           1.0           1.0   
428           3      PConc       4.0       3.0           1.0           6.0   
664           3      PConc       5.0       3.0           2.0           6.0   
1321          3     CBlock       0.0       0.0           0.0           0.0   
654           4      PConc       4.0       3.0           4.0           6.0   
1368          3      PConc       4.0       3.0           3.0           6.0   
1411          4     CBlock       3.0       3.0           1.0           4.0   
584           3     BrkTil       3.0       3.0           1.0           1.0   
956           3     CBlo

### 4. OneHotEncoding the categorical ordinal columns

In [13]:
#Removing already dropped columns from the OHE column scope
for i in set(categorical_ordinal_columns).intersection(drop_coulmns):
  categorical_ordinal_columns.remove(i)

In [14]:
from sklearn.preprocessing import OneHotEncoder

#Declaring the encoder
onehot_encoder = OneHotEncoder(sparse=False,handle_unknown='ignore')
onehot_encoder=onehot_encoder.fit(df[categorical_ordinal_columns])

#Transforming the data
onehot_encoded = onehot_encoder.transform(df[categorical_ordinal_columns])
ohe_columns=onehot_encoder.get_feature_names_out(categorical_ordinal_columns)
df_ip_ohe=pd.DataFrame(onehot_encoded,columns=ohe_columns)

#Replacing the original data with OneHotEncoded data
df_ip.drop(categorical_ordinal_columns,axis=1,inplace=True)
df_ip= pd.merge(df_ip, df_ip_ohe, left_index=True, right_index=True)

print('Shape',df_ip.shape)
df_ip.sample(10)

/usr/local/lib/python3.9/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


Shape (1460, 222)


Id  MSSubClass  LotFrontage  LotArea  LotShape  OverallQual  \
1315  1316          60         85.0    11075         3            6   
1321  1322          20         60.0     6627         2            3   
573    574          80         76.0     9967         2            7   
543    544         120         34.0     4058         3            7   
1405  1406         120         44.0     3842         2            8   
251    252         120         44.0     4750         2            8   
198    199          75         92.0     5520         3            6   
435    436          60         43.0    10667         3            7   
717    718          20         80.0    10000         3            5   
797    798          20         57.0     7677         3            5   

      OverallCond  MasVnrArea  ExterQual  ExterCond  BsmtQual  BsmtCond  \
1315            5         0.0          3          3       2.0       3.0   
1321            6         0.0          3          3       0.0       0.0   
573             5         0.0          3          3       4.0       3.0   
543             5       182.0          3          3       4.0       3.0   
1405            5       174.0          4          3       5.0       3.0   
251             5       481.0          4          3       4.0       3.0   
198             6         0.0          3          3       3.0       3.0   
435             6         0.0          4          3       4.0       3.0   
717             6         0.0          3          3       4.0       3.0   
797             5         0.0          3          3       3.0       3.0   

      BsmtExposure  BsmtFinType1  BsmtFinSF1  BsmtFinType2  BsmtFinSF2  \
1315           2.0           5.0         500           2.0         276   
1321           0.0           0.0           0           0.0           0   
573            1.0           1.0           0           1.0           0   
543            3.0           6.0         584           2.0         139   
1405           4.0           6.0        1373           1.0           0   
251            4.0           6.0        1573           1.0           0   
198            1.0           1.0           0           1.0           0   
435            3.0           6.0         385           5.0         344   
717            1.0           4.0        1084           1.0           0   
797            1.0           4.0         570           1.0           0   

      BsmtUnfSF  TotalBsmtSF  HeatingQC  CentralAir  1stFlrSF  2ndFlrSF  \
1315        176          952          3           1      1092      1020   
1321          0            0          3           0       720         0   
573         384          384          5           1       774       656   
543           0          723          5           1       767         0   
1405        221         1594          5           1      1646         0   
251           0         1573          5           1      1625         0   
198         755          755          5           1       929       929   
435          70          799          5           1       827       834   
717          92         1176          4           1      1178         0   
797         203          773          4           1       773         0   

      LowQualFinSF  GrLivArea  BsmtFullBath  BsmtHalfBath  FullBath  HalfBath  \
1315             0       2112             0             0         2         1   
1321             0        720             0             0         1         0   
573              0       1430             0             0         2         1   
543              0        767             1             0         1         0   
1405             0       1646             1             1         2         0   
251              0       1625             1             1         2         0   
198            371       2229             0             0         1         0   
435              0       1661             1             0         2         1   
717              0       1178 

In [23]:
#Saving the preprecessed data for model building

FinalData=df_ip.copy()
FinalData['SalePrice']=df_op['SalePrice']

FinalData.to_csv('/content/drive/MyDrive/Projects/Kaggle/02. House Price Prediction/01. DataSet/01_Preprocessed_data.csv',index= False)